### ISSUE TITLE
CDT installation failed

### ISSUE THREAD

**Issue by rijaf-iri** [rijaf-iri/CDT#1]
1st test

**Comment by pHking1** [comment]
Sorry, I need your help in solving the following error?
**(Error in setwd(wd): cannot change working directory)** 
This happens when I want to start a CDT by entering this command "startCDT ()"

**Comment by rijaf-iri** [comment]
> Sorry, I need your help in solving the following error?
> **(Error in setwd(wd): cannot change working directory)**
> This happens when I want to start a CDT by entering this command "startCDT ()"

This error means that you renamed or moved or deleted the folder you used as working directory. Use the following command to start CDT with a new working directory

```
startCDT(wd = '~')
```
When CDT GUI is opening, go to the menu File > Configuration to change the working directory
