### ISSUE TITLE
Error in merging temperature

### ISSUE THREAD

**Issue by jpcho89** [rijaf-iri/CDT#10]
I want to merge reanalysis-based grid data and our actual observation data set and I got below error.
    Merge data ... 
    Error in FUN(jloop) : task 1 failed - "second argument must be a list" 
    Temperature merging failed 

I am currently using CDT v6.5 as below
- Gridding --> Merging Temperature Data --> Merging
- Set Date Range: 2018/01/01~2018/1/31 using daily data
- using station data with 60 weather stations as CDT format
- using temperature data which was created by CDT through "Apply Bias Correction"

I attached input files for your understands.

[CDT_Daily-tmax.txt](https://github.com/rijaf-iri/CDT/files/4841478/CDT_Daily-tmax.txt)
[ADJUSTED_Temp_Data_112018_31122018.zip](https://github.com/rijaf-iri/CDT/files/4841480/ADJUSTED_Temp_Data_112018_31122018.zip)

**Comment by rijaf-iri** [comment]
Fixed https://github.com/rijaf-iri/CDT/commit/ff4a98df241f823191289a452649257ee3362444
