### ISSUE TITLE
install osx

### ISSUE THREAD

**Issue by fipoucat** [rijaf-iri/CDT#11]
I am trying to install CDT on mac, followed all steps and finally got an error at CDT install step from github.

  
* installing *source* package ‘CDT’ ...
** using non-staged installation via StagedInstall field
** libs
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c  barnes_routines.f95 -o barnes_routines.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c cdtinterpol_init.c -o cdtinterpol_init.o
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c  cressman_routines.f95 -o cressman_routines.o
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c  distance_routines.f95 -o distance_routines.o
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c  idw_routines.f95 -o idw_routines.o
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c  ordinarykriging_routines.f95 -o ordinarykriging_routines.o
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c  shepard_routines.f95 -o shepard_routines.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c solve_modules.c -o solve_modules.o
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c  spheremap_routines.f95 -o spheremap_routines.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o CDT.so barnes_routines.o cdtinterpol_init.o cressman_routines.o distance_routines.o idw_routines.o ordinarykriging_routines.o shepard_routines.o solve_modules.o spheremap_routines.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
installing to /Library/Frameworks/R.framework/Versions/4.0/Resources/library/CDT/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘CDT’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/CDT/libs/CDT.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/CDT/libs/CDT.so, 6): Symbol not found: ___addtf3
  Referenced from: /usr/local/lib/libquadmath.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/lib/libquadmath.0.dylib
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/CDT’
Error: Failed to install 'CDT' from GitHub:
  (converted from warning) installation of package ‘/var/folders/wb/pry3ghxn4s30_yrgyynbrxs80000gn/T//RtmplMlzPy/fileac2d18f3fa90/CDT_6.5.tar.gz’ had non-zero exit status

Hope hint to fix this error.

Best regards

**Comment by rijaf-iri** [comment]
> I am trying to install CDT on mac, followed all steps and finally got an error at CDT install step from github.
> 
> * installing _source_ package ‘CDT’ ...
>   ** using non-staged installation via StagedInstall field
>   ** libs
>   gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c  barnes_routines.f95 -o barnes_routines.o
>   clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c cdtinterpol_init.c -o cdtinterpol_init.o
>   gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c  cressman_routines.f95 -o cressman_routines.o
>   gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c  distance_routines.f95 -o distance_routines.o
>   gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c  idw_routines.f95 -o idw_routines.o
>   gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c  ordinarykriging_routines.f95 -o ordinarykriging_routines.o
>   gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c  shepard_routines.f95 -o shepard_routines.o
>   clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c solve_modules.c -o solve_modules.o
>   gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c  spheremap_routines.f95 -o spheremap_routines.o
>   clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o CDT.so barnes_routines.o cdtinterpol_init.o cressman_routines.o distance_routines.o idw_routines.o ordinarykriging_routines.o shepard_routines.o solve_modules.o spheremap_routines.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
>   ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
>   ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
>   installing to /Library/Frameworks/R.framework/Versions/4.0/Resources/library/CDT/libs
>   ** R
>   ** inst
>   ** byte-compile and prepare package for lazy loading
>   ** help
>   *** installing help indices
>   ** building package indices
>   ** testing if installed package can be loaded
>   Error: package or namespace load failed for ‘CDT’ in dyn.load(file, DLLpath = DLLpath, ...):
>   unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/CDT/libs/CDT.so':
>   dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/CDT/libs/CDT.so, 6): Symbol not found: ___addtf3
>   Referenced from: /usr/local/lib/libquadmath.0.dylib
>   Expected in: /usr/lib/libSystem.B.dylib
>   in /usr/local/lib/libquadmath.0.dylib
>   Error: loading failed
>   Execution halted
>   ERROR: loading failed
> * removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/CDT’
>   Error: Failed to install 'CDT' from GitHub:
>   (converted from warning) installation of package ‘/var/folders/wb/pry3ghxn4s30_yrgyynbrxs80000gn/T//RtmplMlzPy/fileac2d18f3fa90/CDT_6.5.tar.gz’ had non-zero exit status
> 
> Hope hint to fix this error.
> 
> Best regards

This error means that the dynamic library for gfortran is not found, it seems that it is not in the  folders `/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0` or `/usr/local/gfortran/lib`, these could be the standard path according to your installation. So you have to specify the exact path to gfortran library. Find the folder containing the file `libgfortran.dylib`, when you find it, remember the path to this file.
Open a Terminal and create a folder called `.R` (it's a hidden folder, the dot is matter) under your home directory, go inside the `.R` folder and create a file named `Makevars`, edit this file. All those  commands look  as follows

```
cd ~
mkdir .R
cd .R
touch Makevars
vi Makevars
```

and add the following 3 lines  in it,

```
## replace  this path  with the path where is your  gfortran 
F77 = /usr/local/bin/gfortran
FC = /usr/local/bin/gfortran -mmacosx-version-min=10.13
## replace /usr/local/Cellar/gcc/10.2.0/lib/gcc/10 with the path containing the file libgfortran.dylib in your computer
FLIBS = -L/usr/local/Cellar/gcc/10.2.0/lib/gcc/10 -lgfortran -lquadmath -lm
```
Save the file and restart R. You can try to reinstall CDT using

devtools::install_github("rijaf-iri/CDT")

**Comment by pHking1** [comment]
Thank you. the solution has worked for me.
