### ISSUE TITLE
converting netcdf to cdt format version 6 error

### ISSUE THREAD

**Issue by gkabaka** [rijaf-iri/CDT#6]
When converting netcdf files to CDT format it bring this error:

Error in e$fun(obj, substitute(ex), parent.frame(), e$data) :  unable to find variable "col.idx"
CDT dataset creation values failed

**Comment by Iyakaremyevedaste** [comment]
@gkabaka issue was fixed. Just update your CDT. Thanks @rijaf-iri for fixing error.

**Comment by waswapeter** [comment]
netCDF data not found 
CDT dataset creation values failed
