### ISSUE TITLE
error opening netcdf file

### ISSUE THREAD

**Issue by gkabaka** [rijaf-iri/CDT#9]
the CDT creates a blank dialogue box, both in the version 5 and version 6. as bellow.
<img width="959" alt="cdt_error_screen" src="https://user-images.githubusercontent.com/52150264/85669819-e599d580-b6c8-11ea-943d-6ab2628ea7cb.png">

**Comment by gkabaka** [comment]
the netcdf file sample is
[rr_mrg_201612.zip](https://github.com/rijaf-iri/CDT/files/4829501/rr_mrg_201612.zip)

**Comment by rijaf-iri** [comment]
Fixed
